[tool.flake8]
max-line-length = 88
extend-ignore = "E203"
docstring-convention = "numpy"

[tool.black]
force-exclude = """
(
  /(
    gateware/logic
   | gateware/lowlevel
   | gateware/linien_module.py
   | linien-server/linien_server/csrmap.py
   )/
)
"""

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
plt_dirname = "tests/plots"

# don't complain about plt_dirname
filterwarnings = "ignore::pytest.PytestConfigWarning"

markers = """slow : marks tests as slow (deselect with '-m "not slow"')"""

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
exclude = ["[^/]+/build/"]

[[tool.mypy.overrides]]
module = [
  "linien_common.*",
  "linien_client.*",
  "rpyc.*",
  "fabric",
  "setuptools.*",
  "scipy.*",
  "cma.*",
  "pyrp3.*",
  "pylpsd.*",
  "pyqtgraph.*",
  "fire",
  "influxdb_client.*",
]
ignore_missing_imports = true
