#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

# the server is started in a screen session
apt-get install screen

# monitoradvanced is required for manipulating FPGA registers
cd /tmp
git clone https://github.com/RedPitaya/RedPitaya.git
cd RedPitaya/Test/monitoradvanced
make
cp monitoradvanced /usr/bin

# install pyrp3
cd /tmp
git clone https://github.com/hermitdemschoenenleben/pyrp3.git
cd pyrp3
python3 setup.py install

# install pyrp2
cd /tmp
git clone https://github.com/hermitdemschoenenleben/pyrp.git
cd pyrp
python2.7 setup.py install

# build monitor shared library
cd monitor
make
cp libmonitor.so /usr/lib/