#!/bin/bash

# use
# git init redpid
# cd redpid
# git config --local receive.denyCurrentBranch ignore
# ln -s ../../hooks/post-receive .git/hooks/

cd ..
unset GIT_DIR
git checkout -f
git reset --hard

echo "
. ~/py/bin/activate
git show HEAD
python make.py
" | at now
